services:
  - docker

script:
  - echo 1

before_deploy:
  - docker pull wkevina/godot
  - docker run -v $(pwd):/game-files/ wkevina/godot

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/**/*
  skip_cleanup: true
  on:
    tags: true
